directories:
  output: new
  buildResources: build
productName: SharkWallet
appId: com.leon.SharkWallet
copyright: from_Li
nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  installerIcon: ./img/logo3.ico
  uninstallerIcon: ./img/logo3.ico
  installerHeaderIcon: ./img/logo3.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SharkWallet
publish:
  provider: github
  private: false
  vPrefixedTagName: true
  owner: jarvis0919
  repo: SharkWallet
  token: <stripped sensitive data>
  releaseType: release
win:
  icon: ./img/A.ico
  target:
    target: nsis
    arch: ia32
files: []
electronVersion: 15.1.2
